# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
logging:
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO
    com.inidus.platform: INFO
cdr-connector:
  url: 'http://178.62.71.220:8080'
  username: guest
  password: guest
  is-token-auth: true
server:
  port: 8081

---
spring:
  profiles: marand
cdr-connector:
  url: 'https://cdr.code4health.org/'
  username: a81f47c6-a757-4e34-b644-3ccc62b4a01c
  password: $2a$10$619ki
  is-token-auth: false
server:
  port: 8082

---
spring:
  profiles: ethercis
cdr-connector:
  url: 'http://178.62.71.220:8080'
  username: guest
  password: guest
  is-token-auth: true
server:
  port: 8083